// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chunk.proto
// Protobuf C++ Version: 6.33.1

#ifndef chunk_2eproto_2epb_2eh
#define chunk_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_chunk_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_chunk_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_chunk_2eproto;
}  // extern "C"
namespace world {
class Block;
struct BlockDefaultTypeInternal;
extern BlockDefaultTypeInternal _Block_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Block_class_data_;
class Chunk;
struct ChunkDefaultTypeInternal;
extern ChunkDefaultTypeInternal _Chunk_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Chunk_class_data_;
}  // namespace world
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace world {

// ===================================================================


// -------------------------------------------------------------------

class Block final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:world.Block) */ {
 public:
  inline Block() : Block(nullptr) {}
  ~Block() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Block* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Block));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Block(::google::protobuf::internal::ConstantInitialized);

  inline Block(const Block& from) : Block(nullptr, from) {}
  inline Block(Block&& from) noexcept
      : Block(nullptr, ::std::move(from)) {}
  inline Block& operator=(const Block& from) {
    CopyFrom(from);
    return *this;
  }
  inline Block& operator=(Block&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Block& default_instance() {
    return *reinterpret_cast<const Block*>(
        &_Block_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Block& a, Block& b) { a.Swap(&b); }
  inline void Swap(Block* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Block* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Block* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Block>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Block& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Block& from) { Block::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Block* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "world.Block"; }

  explicit Block(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Block(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Block& from);
  Block(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Block&& from) noexcept
      : Block(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 5,
    kNamespaceFieldNumber = 2,
    kTextureFieldNumber = 3,
    kDataFieldNumber = 4,
    kIdFieldNumber = 1,
    kMaterialTypeFieldNumber = 6,
    kResistanceFieldNumber = 7,
    kEntitiesPassableFieldNumber = 8,
  };
  // repeated float position = 5;
  int position_size() const;
  private:
  int _internal_position_size() const;

  public:
  void clear_position() ;
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::google::protobuf::RepeatedField<float>& position() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_position();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_position() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // string namespace = 2;
  void clear_namespace_() ;
  const ::std::string& namespace_() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_namespace_(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_namespace_();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_namespace_();
  void set_allocated_namespace_(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_namespace_() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_namespace_(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_namespace_();

  public:
  // string texture = 3;
  void clear_texture() ;
  const ::std::string& texture() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_texture(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_texture();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_texture();
  void set_allocated_texture(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_texture() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_texture(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_texture();

  public:
  // string data = 4;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // int32 material_type = 6;
  void clear_material_type() ;
  ::int32_t material_type() const;
  void set_material_type(::int32_t value);

  private:
  ::int32_t _internal_material_type() const;
  void _internal_set_material_type(::int32_t value);

  public:
  // int32 resistance = 7;
  void clear_resistance() ;
  ::int32_t resistance() const;
  void set_resistance(::int32_t value);

  private:
  ::int32_t _internal_resistance() const;
  void _internal_set_resistance(::int32_t value);

  public:
  // int32 entities_passable = 8;
  void clear_entities_passable() ;
  ::int32_t entities_passable() const;
  void set_entities_passable(::int32_t value);

  private:
  ::int32_t _internal_entities_passable() const;
  void _internal_set_entities_passable(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:world.Block)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 48,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Block& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> position_;
    ::google::protobuf::internal::ArenaStringPtr namespace__;
    ::google::protobuf::internal::ArenaStringPtr texture_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::int32_t id_;
    ::int32_t material_type_;
    ::int32_t resistance_;
    ::int32_t entities_passable_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chunk_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Block_class_data_;
// -------------------------------------------------------------------

class Chunk final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:world.Chunk) */ {
 public:
  inline Chunk() : Chunk(nullptr) {}
  ~Chunk() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Chunk* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Chunk));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Chunk(::google::protobuf::internal::ConstantInitialized);

  inline Chunk(const Chunk& from) : Chunk(nullptr, from) {}
  inline Chunk(Chunk&& from) noexcept
      : Chunk(nullptr, ::std::move(from)) {}
  inline Chunk& operator=(const Chunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline Chunk& operator=(Chunk&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Chunk& default_instance() {
    return *reinterpret_cast<const Chunk*>(
        &_Chunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Chunk& a, Chunk& b) { a.Swap(&b); }
  inline void Swap(Chunk* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Chunk* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Chunk* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Chunk>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Chunk& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Chunk& from) { Chunk::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Chunk* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "world.Chunk"; }

  explicit Chunk(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Chunk(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Chunk& from);
  Chunk(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Chunk&& from) noexcept
      : Chunk(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBlocksFieldNumber = 1,
    kPositionFieldNumber = 2,
    kBiomeFieldNumber = 3,
    kAdditionalDataFieldNumber = 4,
  };
  // repeated .world.Block blocks = 1;
  int blocks_size() const;
  private:
  int _internal_blocks_size() const;

  public:
  void clear_blocks() ;
  ::world::Block* PROTOBUF_NONNULL mutable_blocks(int index);
  ::google::protobuf::RepeatedPtrField<::world::Block>* PROTOBUF_NONNULL mutable_blocks();

  private:
  const ::google::protobuf::RepeatedPtrField<::world::Block>& _internal_blocks() const;
  ::google::protobuf::RepeatedPtrField<::world::Block>* PROTOBUF_NONNULL _internal_mutable_blocks();
  public:
  const ::world::Block& blocks(int index) const;
  ::world::Block* PROTOBUF_NONNULL add_blocks();
  const ::google::protobuf::RepeatedPtrField<::world::Block>& blocks() const;
  // repeated float position = 2;
  int position_size() const;
  private:
  int _internal_position_size() const;

  public:
  void clear_position() ;
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::google::protobuf::RepeatedField<float>& position() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_position();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_position() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // string biome = 3;
  void clear_biome() ;
  const ::std::string& biome() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_biome(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_biome();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_biome();
  void set_allocated_biome(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_biome() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_biome(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_biome();

  public:
  // string additional_data = 4;
  void clear_additional_data() ;
  const ::std::string& additional_data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_additional_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_additional_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_additional_data();
  void set_allocated_additional_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_additional_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_additional_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_additional_data();

  public:
  // @@protoc_insertion_point(class_scope:world.Chunk)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 40,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Chunk& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::world::Block > blocks_;
    ::google::protobuf::RepeatedField<float> position_;
    ::google::protobuf::internal::ArenaStringPtr biome_;
    ::google::protobuf::internal::ArenaStringPtr additional_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chunk_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Chunk_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Block

// int32 id = 1;
inline void Block::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t Block::id() const {
  // @@protoc_insertion_point(field_get:world.Block.id)
  return _internal_id();
}
inline void Block::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:world.Block.id)
}
inline ::int32_t Block::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void Block::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string namespace = 2;
inline void Block::clear_namespace_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.namespace__.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Block::namespace_() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:world.Block.namespace)
  return _internal_namespace_();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Block::set_namespace_(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.namespace__.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:world.Block.namespace)
}
inline ::std::string* PROTOBUF_NONNULL Block::mutable_namespace_()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_namespace_();
  // @@protoc_insertion_point(field_mutable:world.Block.namespace)
  return _s;
}
inline const ::std::string& Block::_internal_namespace_() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.namespace__.Get();
}
inline void Block::_internal_set_namespace_(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.namespace__.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Block::_internal_mutable_namespace_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.namespace__.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Block::release_namespace_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:world.Block.namespace)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.namespace__.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.namespace__.Set("", GetArena());
  }
  return released;
}
inline void Block::set_allocated_namespace_(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.namespace__.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.namespace__.IsDefault()) {
    _impl_.namespace__.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:world.Block.namespace)
}

// string texture = 3;
inline void Block::clear_texture() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.texture_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& Block::texture() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:world.Block.texture)
  return _internal_texture();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Block::set_texture(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.texture_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:world.Block.texture)
}
inline ::std::string* PROTOBUF_NONNULL Block::mutable_texture()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_texture();
  // @@protoc_insertion_point(field_mutable:world.Block.texture)
  return _s;
}
inline const ::std::string& Block::_internal_texture() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.texture_.Get();
}
inline void Block::_internal_set_texture(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.texture_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Block::_internal_mutable_texture() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.texture_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Block::release_texture() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:world.Block.texture)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.texture_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.texture_.Set("", GetArena());
  }
  return released;
}
inline void Block::set_allocated_texture(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.texture_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.texture_.IsDefault()) {
    _impl_.texture_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:world.Block.texture)
}

// string data = 4;
inline void Block::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& Block::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:world.Block.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Block::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.data_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:world.Block.data)
}
inline ::std::string* PROTOBUF_NONNULL Block::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:world.Block.data)
  return _s;
}
inline const ::std::string& Block::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void Block::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Block::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Block::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:world.Block.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void Block::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:world.Block.data)
}

// repeated float position = 5;
inline int Block::_internal_position_size() const {
  return _internal_position().size();
}
inline int Block::position_size() const {
  return _internal_position_size();
}
inline void Block::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline float Block::position(int index) const {
  // @@protoc_insertion_point(field_get:world.Block.position)
  return _internal_position().Get(index);
}
inline void Block::set_position(int index, float value) {
  _internal_mutable_position()->Set(index, value);
  // @@protoc_insertion_point(field_set:world.Block.position)
}
inline void Block::add_position(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_position()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:world.Block.position)
}
inline const ::google::protobuf::RepeatedField<float>& Block::position() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:world.Block.position)
  return _internal_position();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL Block::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:world.Block.position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_position();
}
inline const ::google::protobuf::RepeatedField<float>&
Block::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
Block::_internal_mutable_position() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.position_;
}

// int32 material_type = 6;
inline void Block::clear_material_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.material_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t Block::material_type() const {
  // @@protoc_insertion_point(field_get:world.Block.material_type)
  return _internal_material_type();
}
inline void Block::set_material_type(::int32_t value) {
  _internal_set_material_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:world.Block.material_type)
}
inline ::int32_t Block::_internal_material_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.material_type_;
}
inline void Block::_internal_set_material_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.material_type_ = value;
}

// int32 resistance = 7;
inline void Block::clear_resistance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resistance_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t Block::resistance() const {
  // @@protoc_insertion_point(field_get:world.Block.resistance)
  return _internal_resistance();
}
inline void Block::set_resistance(::int32_t value) {
  _internal_set_resistance(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:world.Block.resistance)
}
inline ::int32_t Block::_internal_resistance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resistance_;
}
inline void Block::_internal_set_resistance(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resistance_ = value;
}

// int32 entities_passable = 8;
inline void Block::clear_entities_passable() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entities_passable_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::int32_t Block::entities_passable() const {
  // @@protoc_insertion_point(field_get:world.Block.entities_passable)
  return _internal_entities_passable();
}
inline void Block::set_entities_passable(::int32_t value) {
  _internal_set_entities_passable(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:world.Block.entities_passable)
}
inline ::int32_t Block::_internal_entities_passable() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.entities_passable_;
}
inline void Block::_internal_set_entities_passable(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.entities_passable_ = value;
}

// -------------------------------------------------------------------

// Chunk

// repeated .world.Block blocks = 1;
inline int Chunk::_internal_blocks_size() const {
  return _internal_blocks().size();
}
inline int Chunk::blocks_size() const {
  return _internal_blocks_size();
}
inline void Chunk::clear_blocks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blocks_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::world::Block* PROTOBUF_NONNULL Chunk::mutable_blocks(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:world.Chunk.blocks)
  return _internal_mutable_blocks()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::world::Block>* PROTOBUF_NONNULL Chunk::mutable_blocks()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:world.Chunk.blocks)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_blocks();
}
inline const ::world::Block& Chunk::blocks(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:world.Chunk.blocks)
  return _internal_blocks().Get(index);
}
inline ::world::Block* PROTOBUF_NONNULL Chunk::add_blocks()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::world::Block* _add =
      _internal_mutable_blocks()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:world.Chunk.blocks)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::world::Block>& Chunk::blocks() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:world.Chunk.blocks)
  return _internal_blocks();
}
inline const ::google::protobuf::RepeatedPtrField<::world::Block>&
Chunk::_internal_blocks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.blocks_;
}
inline ::google::protobuf::RepeatedPtrField<::world::Block>* PROTOBUF_NONNULL
Chunk::_internal_mutable_blocks() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.blocks_;
}

// repeated float position = 2;
inline int Chunk::_internal_position_size() const {
  return _internal_position().size();
}
inline int Chunk::position_size() const {
  return _internal_position_size();
}
inline void Chunk::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline float Chunk::position(int index) const {
  // @@protoc_insertion_point(field_get:world.Chunk.position)
  return _internal_position().Get(index);
}
inline void Chunk::set_position(int index, float value) {
  _internal_mutable_position()->Set(index, value);
  // @@protoc_insertion_point(field_set:world.Chunk.position)
}
inline void Chunk::add_position(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_position()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:world.Chunk.position)
}
inline const ::google::protobuf::RepeatedField<float>& Chunk::position() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:world.Chunk.position)
  return _internal_position();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL Chunk::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:world.Chunk.position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_position();
}
inline const ::google::protobuf::RepeatedField<float>&
Chunk::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
Chunk::_internal_mutable_position() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.position_;
}

// string biome = 3;
inline void Chunk::clear_biome() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.biome_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& Chunk::biome() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:world.Chunk.biome)
  return _internal_biome();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Chunk::set_biome(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.biome_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:world.Chunk.biome)
}
inline ::std::string* PROTOBUF_NONNULL Chunk::mutable_biome()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_biome();
  // @@protoc_insertion_point(field_mutable:world.Chunk.biome)
  return _s;
}
inline const ::std::string& Chunk::_internal_biome() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.biome_.Get();
}
inline void Chunk::_internal_set_biome(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.biome_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Chunk::_internal_mutable_biome() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.biome_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Chunk::release_biome() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:world.Chunk.biome)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.biome_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.biome_.Set("", GetArena());
  }
  return released;
}
inline void Chunk::set_allocated_biome(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.biome_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.biome_.IsDefault()) {
    _impl_.biome_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:world.Chunk.biome)
}

// string additional_data = 4;
inline void Chunk::clear_additional_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.additional_data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& Chunk::additional_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:world.Chunk.additional_data)
  return _internal_additional_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Chunk::set_additional_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.additional_data_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:world.Chunk.additional_data)
}
inline ::std::string* PROTOBUF_NONNULL Chunk::mutable_additional_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_additional_data();
  // @@protoc_insertion_point(field_mutable:world.Chunk.additional_data)
  return _s;
}
inline const ::std::string& Chunk::_internal_additional_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.additional_data_.Get();
}
inline void Chunk::_internal_set_additional_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.additional_data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Chunk::_internal_mutable_additional_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.additional_data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Chunk::release_additional_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:world.Chunk.additional_data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.additional_data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.additional_data_.Set("", GetArena());
  }
  return released;
}
inline void Chunk::set_allocated_additional_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.additional_data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.additional_data_.IsDefault()) {
    _impl_.additional_data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:world.Chunk.additional_data)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace world


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // chunk_2eproto_2epb_2eh
