// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chunk.proto
// Protobuf C++ Version: 6.33.1

#include "chunk.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace world {

inline constexpr Block::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_{},
        namespace__(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        texture_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        material_type_{0},
        resistance_{0},
        entities_passable_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Block::Block(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Block_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BlockDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BlockDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BlockDefaultTypeInternal() {}
  union {
    Block _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BlockDefaultTypeInternal _Block_default_instance_;

inline constexpr Chunk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        blocks_{},
        position_{},
        biome_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        additional_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Chunk::Chunk(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Chunk_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChunkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChunkDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChunkDefaultTypeInternal() {}
  union {
    Chunk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChunkDefaultTypeInternal _Chunk_default_instance_;
}  // namespace world
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_chunk_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_chunk_2eproto = nullptr;
const ::uint32_t
    TableStruct_chunk_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::world::Block, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::world::Block, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::world::Block, _impl_.namespace__),
        PROTOBUF_FIELD_OFFSET(::world::Block, _impl_.texture_),
        PROTOBUF_FIELD_OFFSET(::world::Block, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::world::Block, _impl_.position_),
        PROTOBUF_FIELD_OFFSET(::world::Block, _impl_.material_type_),
        PROTOBUF_FIELD_OFFSET(::world::Block, _impl_.resistance_),
        PROTOBUF_FIELD_OFFSET(::world::Block, _impl_.entities_passable_),
        4,
        1,
        2,
        3,
        0,
        5,
        6,
        7,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::world::Chunk, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::world::Chunk, _impl_.blocks_),
        PROTOBUF_FIELD_OFFSET(::world::Chunk, _impl_.position_),
        PROTOBUF_FIELD_OFFSET(::world::Chunk, _impl_.biome_),
        PROTOBUF_FIELD_OFFSET(::world::Chunk, _impl_.additional_data_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::world::Block)},
        {19, sizeof(::world::Chunk)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::world::_Block_default_instance_._instance,
    &::world::_Chunk_default_instance_._instance,
};
const char descriptor_table_protodef_chunk_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013chunk.proto\022\005world\"\235\001\n\005Block\022\n\n\002id\030\001 \001"
    "(\005\022\021\n\tnamespace\030\002 \001(\t\022\017\n\007texture\030\003 \001(\t\022\014"
    "\n\004data\030\004 \001(\t\022\020\n\010position\030\005 \003(\002\022\025\n\rmateri"
    "al_type\030\006 \001(\005\022\022\n\nresistance\030\007 \001(\005\022\031\n\021ent"
    "ities_passable\030\010 \001(\005\"_\n\005Chunk\022\034\n\006blocks\030"
    "\001 \003(\0132\014.world.Block\022\020\n\010position\030\002 \003(\002\022\r\n"
    "\005biome\030\003 \001(\t\022\027\n\017additional_data\030\004 \001(\tb\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_chunk_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_chunk_2eproto = {
    false,
    false,
    285,
    descriptor_table_protodef_chunk_2eproto,
    "chunk.proto",
    &descriptor_table_chunk_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_chunk_2eproto::offsets,
    file_level_enum_descriptors_chunk_2eproto,
    file_level_service_descriptors_chunk_2eproto,
};
namespace world {
// ===================================================================

class Block::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Block>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Block, _impl_._has_bits_);
};

Block::Block(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Block_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:world.Block)
}
PROTOBUF_NDEBUG_INLINE Block::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::world::Block& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        position_{visibility, arena, from.position_},
        namespace__(arena, from.namespace__),
        texture_(arena, from.texture_),
        data_(arena, from.data_) {}

Block::Block(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Block& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Block_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Block* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, entities_passable_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::entities_passable_));

  // @@protoc_insertion_point(copy_constructor:world.Block)
}
PROTOBUF_NDEBUG_INLINE Block::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        position_{visibility, arena},
        namespace__(arena),
        texture_(arena),
        data_(arena) {}

inline void Block::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, entities_passable_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::entities_passable_));
}
Block::~Block() {
  // @@protoc_insertion_point(destructor:world.Block)
  SharedDtor(*this);
}
inline void Block::SharedDtor(MessageLite& self) {
  Block& this_ = static_cast<Block&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.namespace__.Destroy();
  this_._impl_.texture_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Block::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Block(arena);
}
constexpr auto Block::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Block, _impl_.position_) +
          decltype(Block::_impl_.position_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Block), alignof(Block), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Block::PlacementNew_,
                                 sizeof(Block),
                                 alignof(Block));
  }
}
constexpr auto Block::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Block_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Block::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Block>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Block::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Block>(), &Block::ByteSizeLong,
              &Block::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Block, _impl_._cached_size_),
          false,
      },
      &Block::kDescriptorMethods,
      &descriptor_table_chunk_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Block_class_data_ =
        Block::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Block::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Block_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Block_class_data_.tc_table);
  return Block_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 48, 2>
Block::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Block, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Block_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::world::Block>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 entities_passable = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Block, _impl_.entities_passable_), 7>(),
     {64, 7, 0,
      PROTOBUF_FIELD_OFFSET(Block, _impl_.entities_passable_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Block, _impl_.id_), 4>(),
     {8, 4, 0,
      PROTOBUF_FIELD_OFFSET(Block, _impl_.id_)}},
    // string namespace = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(Block, _impl_.namespace__)}},
    // string texture = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(Block, _impl_.texture_)}},
    // string data = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 3, 0,
      PROTOBUF_FIELD_OFFSET(Block, _impl_.data_)}},
    // repeated float position = 5;
    {::_pbi::TcParser::FastF32P1,
     {42, 0, 0,
      PROTOBUF_FIELD_OFFSET(Block, _impl_.position_)}},
    // int32 material_type = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Block, _impl_.material_type_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(Block, _impl_.material_type_)}},
    // int32 resistance = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Block, _impl_.resistance_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(Block, _impl_.resistance_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Block, _impl_.id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string namespace = 2;
    {PROTOBUF_FIELD_OFFSET(Block, _impl_.namespace__), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string texture = 3;
    {PROTOBUF_FIELD_OFFSET(Block, _impl_.texture_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string data = 4;
    {PROTOBUF_FIELD_OFFSET(Block, _impl_.data_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated float position = 5;
    {PROTOBUF_FIELD_OFFSET(Block, _impl_.position_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // int32 material_type = 6;
    {PROTOBUF_FIELD_OFFSET(Block, _impl_.material_type_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 resistance = 7;
    {PROTOBUF_FIELD_OFFSET(Block, _impl_.resistance_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 entities_passable = 8;
    {PROTOBUF_FIELD_OFFSET(Block, _impl_.entities_passable_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\13\0\11\7\4\0\0\0\0\0\0\0\0\0\0\0"
    "world.Block"
    "namespace"
    "texture"
    "data"
  }},
};
PROTOBUF_NOINLINE void Block::Clear() {
// @@protoc_insertion_point(message_clear_start:world.Block)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.position_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.namespace__.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.texture_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f0U)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.entities_passable_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.entities_passable_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Block::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Block& this_ = static_cast<const Block&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Block::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Block& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:world.Block)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_id(), target);
    }
  }

  // string namespace = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_namespace_().empty()) {
      const ::std::string& _s = this_._internal_namespace_();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "world.Block.namespace");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string texture = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_texture().empty()) {
      const ::std::string& _s = this_._internal_texture();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "world.Block.texture");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string data = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "world.Block.data");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // repeated float position = 5;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    if (this_._internal_position_size() > 0) {
      target = stream->WriteFixedPacked(5, this_._internal_position(), target);
    }
  }

  // int32 material_type = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_material_type() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
              stream, this_._internal_material_type(), target);
    }
  }

  // int32 resistance = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_resistance() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<7>(
              stream, this_._internal_resistance(), target);
    }
  }

  // int32 entities_passable = 8;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_entities_passable() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<8>(
              stream, this_._internal_entities_passable(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:world.Block)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Block::ByteSizeLong(const MessageLite& base) {
  const Block& this_ = static_cast<const Block&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Block::ByteSizeLong() const {
  const Block& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:world.Block)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated float position = 5;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_position_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // string namespace = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_namespace_().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_namespace_());
      }
    }
    // string texture = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_texture().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_texture());
      }
    }
    // string data = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_data());
      }
    }
    // int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_id());
      }
    }
    // int32 material_type = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_material_type() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_material_type());
      }
    }
    // int32 resistance = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_resistance() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_resistance());
      }
    }
    // int32 entities_passable = 8;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_entities_passable() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_entities_passable());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Block::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Block*>(&to_msg);
  auto& from = static_cast<const Block&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:world.Block)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_position()->MergeFrom(from._internal_position());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_namespace_().empty()) {
        _this->_internal_set_namespace_(from._internal_namespace_());
      } else {
        if (_this->_impl_.namespace__.IsDefault()) {
          _this->_internal_set_namespace_("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_texture().empty()) {
        _this->_internal_set_texture(from._internal_texture());
      } else {
        if (_this->_impl_.texture_.IsDefault()) {
          _this->_internal_set_texture("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_material_type() != 0) {
        _this->_impl_.material_type_ = from._impl_.material_type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_resistance() != 0) {
        _this->_impl_.resistance_ = from._impl_.resistance_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_entities_passable() != 0) {
        _this->_impl_.entities_passable_ = from._impl_.entities_passable_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Block::CopyFrom(const Block& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:world.Block)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Block::InternalSwap(Block* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.position_.InternalSwap(&other->_impl_.position_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.namespace__, &other->_impl_.namespace__, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.texture_, &other->_impl_.texture_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Block, _impl_.entities_passable_)
      + sizeof(Block::_impl_.entities_passable_)
      - PROTOBUF_FIELD_OFFSET(Block, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Block::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Chunk::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Chunk>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Chunk, _impl_._has_bits_);
};

Chunk::Chunk(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Chunk_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:world.Chunk)
}
PROTOBUF_NDEBUG_INLINE Chunk::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::world::Chunk& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        blocks_{visibility, arena, from.blocks_},
        position_{visibility, arena, from.position_},
        biome_(arena, from.biome_),
        additional_data_(arena, from.additional_data_) {}

Chunk::Chunk(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Chunk& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Chunk_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Chunk* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:world.Chunk)
}
PROTOBUF_NDEBUG_INLINE Chunk::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        blocks_{visibility, arena},
        position_{visibility, arena},
        biome_(arena),
        additional_data_(arena) {}

inline void Chunk::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Chunk::~Chunk() {
  // @@protoc_insertion_point(destructor:world.Chunk)
  SharedDtor(*this);
}
inline void Chunk::SharedDtor(MessageLite& self) {
  Chunk& this_ = static_cast<Chunk&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.biome_.Destroy();
  this_._impl_.additional_data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Chunk::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Chunk(arena);
}
constexpr auto Chunk::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Chunk, _impl_.blocks_) +
          decltype(Chunk::_impl_.blocks_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Chunk, _impl_.position_) +
          decltype(Chunk::_impl_.position_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Chunk), alignof(Chunk), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Chunk::PlacementNew_,
                                 sizeof(Chunk),
                                 alignof(Chunk));
  }
}
constexpr auto Chunk::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Chunk_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Chunk::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Chunk>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Chunk::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Chunk>(), &Chunk::ByteSizeLong,
              &Chunk::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Chunk, _impl_._cached_size_),
          false,
      },
      &Chunk::kDescriptorMethods,
      &descriptor_table_chunk_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Chunk_class_data_ =
        Chunk::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Chunk::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Chunk_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Chunk_class_data_.tc_table);
  return Chunk_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 40, 2>
Chunk::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Chunk, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Chunk_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::world::Chunk>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string additional_data = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 3, 0,
      PROTOBUF_FIELD_OFFSET(Chunk, _impl_.additional_data_)}},
    // repeated .world.Block blocks = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Chunk, _impl_.blocks_)}},
    // repeated float position = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(Chunk, _impl_.position_)}},
    // string biome = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(Chunk, _impl_.biome_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .world.Block blocks = 1;
    {PROTOBUF_FIELD_OFFSET(Chunk, _impl_.blocks_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated float position = 2;
    {PROTOBUF_FIELD_OFFSET(Chunk, _impl_.position_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // string biome = 3;
    {PROTOBUF_FIELD_OFFSET(Chunk, _impl_.biome_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string additional_data = 4;
    {PROTOBUF_FIELD_OFFSET(Chunk, _impl_.additional_data_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::world::Block>()},
  }},
  {{
    "\13\0\0\5\17\0\0\0"
    "world.Chunk"
    "biome"
    "additional_data"
  }},
};
PROTOBUF_NOINLINE void Chunk::Clear() {
// @@protoc_insertion_point(message_clear_start:world.Chunk)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.blocks_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.position_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.biome_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.additional_data_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Chunk::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Chunk& this_ = static_cast<const Chunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Chunk::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Chunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:world.Chunk)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .world.Block blocks = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_blocks_size());
         i < n; i++) {
      const auto& repfield = this_._internal_blocks().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated float position = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    if (this_._internal_position_size() > 0) {
      target = stream->WriteFixedPacked(2, this_._internal_position(), target);
    }
  }

  // string biome = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_biome().empty()) {
      const ::std::string& _s = this_._internal_biome();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "world.Chunk.biome");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string additional_data = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_additional_data().empty()) {
      const ::std::string& _s = this_._internal_additional_data();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "world.Chunk.additional_data");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:world.Chunk)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Chunk::ByteSizeLong(const MessageLite& base) {
  const Chunk& this_ = static_cast<const Chunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Chunk::ByteSizeLong() const {
  const Chunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:world.Chunk)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // repeated .world.Block blocks = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_blocks_size();
      for (const auto& msg : this_._internal_blocks()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated float position = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_position_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // string biome = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_biome().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_biome());
      }
    }
    // string additional_data = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_additional_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_additional_data());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Chunk::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Chunk*>(&to_msg);
  auto& from = static_cast<const Chunk&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:world.Chunk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_blocks()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_blocks());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_position()->MergeFrom(from._internal_position());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_biome().empty()) {
        _this->_internal_set_biome(from._internal_biome());
      } else {
        if (_this->_impl_.biome_.IsDefault()) {
          _this->_internal_set_biome("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_additional_data().empty()) {
        _this->_internal_set_additional_data(from._internal_additional_data());
      } else {
        if (_this->_impl_.additional_data_.IsDefault()) {
          _this->_internal_set_additional_data("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Chunk::CopyFrom(const Chunk& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:world.Chunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Chunk::InternalSwap(Chunk* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.blocks_.InternalSwap(&other->_impl_.blocks_);
  _impl_.position_.InternalSwap(&other->_impl_.position_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.biome_, &other->_impl_.biome_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.additional_data_, &other->_impl_.additional_data_, arena);
}

::google::protobuf::Metadata Chunk::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace world
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_chunk_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
